services:
  web:
    container_name: ${WEB_HOST}
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: remote_host=172.17.0.1
      REDIS_URL: ${REDIS_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      API_NINJA_KEY: ${API_NINJA_KEY}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      EMAIL: ${EMAIL]
      EMAIL_PASSWORD: $[EMAIL_PASSWORD}
  redis:
    image: redis:7.0.0
    ports:
      - "6379:6379"
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
